<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24789" started-at="2016-05-21T18:14:07Z" finished-at="2016-05-21T18:14:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24789" started-at="2016-05-21T18:14:07Z" finished-at="2016-05-21T18:14:31Z">
      <class name="login.LoginTeste">
        <test-method status="PASS" signature="inciaTeste()[pri:0, instance:login.LoginTeste@8bd1b6a]" name="inciaTeste" is-config="true" duration-ms="6284" started-at="2016-05-21T15:14:07Z" finished-at="2016-05-21T15:14:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inciaTeste -->
        <test-method status="FAIL" signature="testeLogin()[pri:0, instance:login.LoginTeste@8bd1b6a]" name="testeLogin" duration-ms="18243" started-at="2016-05-21T15:14:13Z" finished-at="2016-05-21T15:14:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Não foi possível realizar o login na aplicação]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Não foi possível realizar o login na aplicação
	at login.LoginTeste.testeLogin(LoginTeste.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testeLogin -->
        <test-method status="PASS" signature="finalizaTeste()[pri:0, instance:login.LoginTeste@8bd1b6a]" name="finalizaTeste" is-config="true" duration-ms="218" started-at="2016-05-21T15:14:31Z" finished-at="2016-05-21T15:14:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizaTeste -->
      </class> <!-- login.LoginTeste -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
